repository_type: pipeline

nf_core_version: 3.5.1

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-fungal_pipeline_logo_light.png
    - docs/images/nf-core-fungal_pipeline_logo_light.png
    - docs/images/nf-core-fungal_pipeline_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-fungal_pipeline_logo_light.png
    - docs/images/nf-core-fungal_pipeline_logo_light.png
    - docs/images/nf-core-fungal_pipeline_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: nf-core
  name: fungal_pipeline
  description: This pipeline is strictly an exercise to refresh my nextflow knowledge
    and build upon it by transcribing one of my existing pipelines into nextflow.
  author: Chris Burgess
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - gpu
  is_nfcore: false
